name: travel_app5b
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-244.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/profile1.jpg
    - assets/img/profile2.jpg
    - assets/img/profile3.jpg
    - assets/img/profile4.jpg
